### ISSUE TITLE
Use System globalName

### ISSUE THREAD

**Issue by guybedford** [HuasoFoundries/systemjs-less-plugin#1]
In https://github.com/InstaGIS/systemjs-less-plugin/blob/master/less-builder.js#L26, rather than directly writing `System`, it is better to use `compileOpts.systemGlobal` as in SFX builds the System global is called `$__System`, which is tracked through this property.

**Comment by ffflabs** [comment]
@guybedford you're right, this has PR #3 on the pipeline to fix that ASAP.

**Comment by guybedford** [comment]
:+1: nice to see the movement there. Just let me know if you need any feeback.
