### ISSUE TITLE
Wrong url processing

### ISSUE THREAD

**Issue by MikeVitik** [HuasoFoundries/systemjs-less-plugin#10]
I try to bundle simple tmp.less file

``` .less
.drop-down-icon {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuNWWFMmUAAABISURBVDhPY2hoaPhPLgZrBgIGUvGoZihOTEzEGrIgcWR1IDGsNqMbgK4RhHFqBmGYAdg0gjBezSCMSyMIE9SMDw91zeThhv8Ami96gQcIp6MAAAAASUVORK5CYII=);
}
```

In config I add
`
  meta: {
    "tmp": {
      deps: [
        "tmp.less!less"
      ]
    }
  },
`
After bundling:
`
jspm bundle tmp
`
I get a wrong result for icon url. Instead of original url(data.. I have url(D:\tmp\LessUrl/data...

``` js
(function(c){var d=document,a='appendChild',i='styleSheet',s=d.createElement('style');s.type='text/css';d.getElementsByTagName('head')[0][a](s);s[i]?s[i].cssText=c:s[a](d.createTextNode(c));})
(".drop-down-icon {\n  background-image: url(D:\\tmp\\LessUrl/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuNWWFMmUAAABISURBVDhPY2hoaPhPLgZrBgIGUvGoZihOTEzEGrIgcWR1IDGsNqMbgK4RhHFqBmGYAdg0gjBezSCMSyMIE9SMDw91zeThhv8Ami96gQcIp6MAAAAASUVORK5CYII=);\n}\n");
```

[lessPlugin.zip](https://github.com/HuasoFoundries/systemjs-less-plugin/files/544016/lessPlugin.zip)

**Comment by MikeVitik** [comment]
I investigate my problem deeper and find out workaround (based on error in your code). But I want to fix it correctly. Will you accept a pull request from me to fix the issue?

**Comment by ffflabs** [comment]
of course I'd be willing to accept a PR. Please contribute.
I've been dealing with image urls and I thought it was a common lessjs problem.

**Comment by ffflabs** [comment]
@MikeVitik is that PR coming? I hate when I have broken urls in my less files.
