### ISSUE TITLE
v2.0.0 - question about overriding/reusing Bootstrap vars/mixins

### ISSUE THREAD

**Issue by ardi-n** [HuasoFoundries/systemjs-less-plugin#14]
Hello,

thank you for your work on this plugin. I see it's about to become an official SystemJS plugin for LESS. 

A lot has changed in the source code. The plugin is now based on standard workflow introduced by css-plugin-base. Since last version of this plugin actual LESS compilation has moved to translate() function because this is the API.

Unfortunately this broke bundling in my project. I deal with legacy Bootstrap v2 styles. I need to override certain core Bootstrap variables and mixins. This was possible before because that version of the plugin concatenated all LESS files before compiling and rebased \@import and url calls. The new version also rebases correctly. But I have no access to core Bootstrap vars in my project styles. And I can't simply \@import (reference) core bootstrap.less because its path varies.

There are LESS plugins that can resolve jspm modules' paths like https://github.com/sebasrodriguez/jspm-less.

This way I'm able to \@import (reference) bootstrap.less in my project styles. But unfortunately SystemJS rebasing of css urls stops working.

Then I came with other solution: I created a Gulp task that appends an \@import to my project overrides to the end of bootstrap.less in its normal location before running jspm bundle. This works but LESS needs to know how to resolve jspm paths. If I manually prepend 
```
var JspmLess = System._nodeRequire("jspm-less");
```
to https://github.com/HuasoFoundries/systemjs-less-plugin/blob/master/src/less.js and add it later during compilation:
```
less.render(style, {
...
plugins: [new JspmLess()]
...
});
```
then jspm is able to compile and bundle LESS. My project styles that are scoped in view components and use some bootstrap vars or mixins must only have \@import (reference) bootstrap.less prepended.

But https://github.com/HuasoFoundries/systemjs-less-plugin/blob/master/src/less.js is supposed to run in browser and in Node. The System._nodeRequire doesn't work in browser when there's a need to dynamically load less files. 

I don't know if I approach the problem correctly. My suggestion is to include JSPM path resolution for LESS directly in the systemjs-less-plugin.

**Comment by ffflabs** [comment]
Perhaps this could be solved by bringing back the logic to concatenate all imports before bundling. The choice of moving towards (teleporting really) the plugin-css spec was made in order to achieve deduplication and optimization via autoprefixer.

If you can live without those optimizations, I'd advise you to stick to v1.9 until I can get a mixin with the best of both releases.

**Comment by ffflabs** [comment]
@ardi-n in #17 support for jspm imports was added, so you can now do

```js
@import "jspm://bootstrap/path/to/file.less";
```

this will resolve to whatever path is mapped to bootstrap in your `jspm.config.js`

You can also import plain `.css` files doing

```js
@import (less) "jspm://packagename/path/to/file.css";
```

please tell me if this works for you.
