### ISSUE TITLE
How to configure the build options [I am using jspm 0.17.0-beta.38]

### ISSUE THREAD

**Issue by fernandogmar** [HuasoFoundries/systemjs-less-plugin#15]
Hi !

I read that "system-less-plugin supports the same [build options](https://github.com/systemjs/plugin-css#builder-support)" as plugin-css. But how exactly they can be set. I am doing this:

```
SystemJS.config({
    rootURL: './public'
});
```

But on building it seems it still looks for the files in the wrong folder. For example `/my-file.less` it is not resolved as `....../public/my-file.less`. It keeps the the same path '/', that is obviously wrong.

Am I missing something?

**Comment by ffflabs** [comment]
Have you solved this issue or it's still resolving to the wrong path?

**Comment by fernandogmar** [comment]
Hi Felipe,

I switched to a different aprox, but still I am curious how [these options](https://github.com/systemjs/plugin-css#builder-support) could be setted using this systemjs-less-plugin
