### ISSUE TITLE
Resolve package paths

### ISSUE THREAD

**Issue by MoonStorm** [HuasoFoundries/systemjs-less-plugin#16]
The only way I could find to reference a package that contains a less file is to use something like ``@import '../../jspm_packages/github/distros/bootstrap-less@3.3.9/bootstrap/index.less'``. Which is obviously going to easily end up in a maintenance nightmare down the road.

The import statement in the ``typescript`` plugin for example properly resolves the package, without any version information attached, unless the paths start with ``.`` or ``..``. 

Is there a way to specify the paths in a similar fashion with this plugin, e.g. ``@import 'bootstrap-less/bootstrap/index.less``?  Thanks.

**Comment by fernandogmar** [comment]
Same here...

I have found that there are some less plugins to manage this:

[jspm-less](https://github.com/sebasrodriguez/jspm-less) 
[less-plugin-jspm-import](https://github.com/lixiaoyan/less-plugin-jspm-import) 

 but no idea how to configure it on this systemjs-less-plugin
[less plugin page](http://lesscss.org/usage/#plugins)

Looking for other alternatives could be just to use a different loader, postCss + less plugin:
[https://github.com/MeoMix/jspm-loader-css](https://github.com/MeoMix/jspm-loader-css)

less plugins for postCSS:
[https://github.com/webschik/postcss-less](https://github.com/webschik/postcss-less)
[https://github.com/Crunch/postcss-less](https://github.com/Crunch/postcss-less)

Any help on this will be welcome ;)

**Comment by fernandogmar** [comment]
Just in case you are interested I have made a Pull Request: [https://github.com/HuasoFoundries/systemjs-less-plugin/pull/17](https://github.com/HuasoFoundries/systemjs-less-plugin/pull/17)

meanwhile  you could use my fork: `jspm install less=github:fernandogmar/systemjs-less-plugin`

**Comment by ffflabs** [comment]
@MoonStorm #17 has been merged. Please try using the latest release.

**Comment by fernandogmar** [comment]
awesome! :+1:
