### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mauron85** [HuasoFoundries/systemjs-less-plugin#19]
Hi there and thanks for this plugin.

Environment:
jspm: 0.17.0-beta.42
systemjs: 0.20.14
systemjs-builder: 0.16.9
systemjs-less-plugin: 2.0.0

When I try to build a static js with systemjs-builder I get error:

```
ReferenceError: window is not defined
```

I've debugged bit and it seems that [this condition](https://github.com/HuasoFoundries/systemjs-less-plugin/blob/master/src/less.js#L15) is not met, because `this.builder` is undefined and that's why less.browser.js is used also in node environment. Not sure why.

**Comment by ffflabs** [comment]
Please see how I'm doing it at https://github.com/HuasoFoundries/systemjs-less-plugin/blob/master/test/test.js  It uses systemjs-builder as

```js
var Builder = require('jspm').Builder,
     builder = new Builder();
```

Could you try using it that way?

**Comment by ffflabs** [comment]
@mauron85 any luck?

**Comment by mauron85** [comment]
@amenadiel I'm currently not using SystemJS. So closing this.  Thank you for help.
