### ISSUE TITLE
Suggestion: reduce verbosity

### ISSUE THREAD

**Issue by ppvg** [HuasoFoundries/systemjs-less-plugin#4]
There are [some](https://github.com/HuasoFoundries/systemjs-less-plugin/blob/master/less.js#L21) [`console`](https://github.com/HuasoFoundries/systemjs-less-plugin/blob/master/less.js#L22).[`log()`](https://github.com/HuasoFoundries/systemjs-less-plugin/blob/master/less.js#L44)s that make this module more verbose than it needs to be IMHO. They seem to have been added for debugging. Are you okay with removing them, or switching to [`debug`](https://www.npmjs.com/package/debug)?

**Comment by ffflabs** [comment]
I agree. Those logs were introduced in a prior PR and I've been meaning to remove them. Thanks.
